config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.shortcuts import redirect
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView
from rest_framework.authtoken.views import obtain_auth_token

urlpatterns = [
    # Translate
    path("i18n/", include("django.conf.urls.i18n")),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    path(
        "about/", TemplateView.as_view(template_name="pages/about.html"), name="about"
    ),
    path(
        "good-practices/",
        TemplateView.as_view(template_name="pages/good-practices.html"),
        name="good-practices",
    ),
    path(
        "codesource/",
        lambda request: redirect("https://github.com/salgadox/unite-compress"),
        name="codesource",
    ),
    path("users/", include("unite_compress.users.urls", namespace="users")),
    path("files/", include("unite_compress.files.urls", namespace="files")),
    path("courses/", include("unite_compress.courses.urls", namespace="courses")),
    path("accounts/", include("allauth.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# API URLS
urlpatterns += [
    # API base url
    path("api/", include("config.api_router")),
    # DRF auth token
    path("auth-token/", obtain_auth_token),
    path("api/schema/", SpectacularAPIView.as_view(), name="api-schema"),
    path(
        "api/docs/",
        SpectacularSwaggerView.as_view(url_name="api-schema"),
        name="api-docs",
    ),
]

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

unite_compress/files/api/urls.py
from django.urls import include, path

from unite_compress.files.api.views import (
    FileDirectUploadFinishApi,
    FileDirectUploadLocalApi,
    FileDirectUploadStartApi,
    FileStandardUploadApi,
)

# Depending on your case, you might want to exclude certain urls, based on the values of
# FILE_UPLOAD_STRATEGY and FILE_UPLOAD_STORAGE
# For the sake fo simplicity and to serve as an example project, we are including
# everything here.
app_name = "file_upload"
urlpatterns = [
    path(
        "upload/",
        include(
            (
                [
                    path("standard/", FileStandardUploadApi.as_view(), name="standard"),
                    path(
                        "direct/",
                        include(
                            (
                                [
                                    path(
                                        "start/",
                                        FileDirectUploadStartApi.as_view(),
                                        name="start",
                                    ),
                                    path(
                                        "finish/",
                                        FileDirectUploadFinishApi.as_view(),
                                        name="finish",
                                    ),
                                    path(
                                        "local/<str:file_id>/",
                                        FileDirectUploadLocalApi.as_view(),
                                        name="local",
                                    ),
                                ],
                                "direct",
                            )
                        ),
                    ),
                ],
                "upload",
            )
        ),
    )
]

unite_compress/files/urls.py
from django.urls import path

from unite_compress.files.views import (
    FileDetailView,
    FileListView,
    FileUploadView,
    file_converting_view,
    latest_file_view,
)

app_name = "files"
urlpatterns = [
    path("", FileListView.as_view(), name="list"),
    path("upload/", FileUploadView.as_view(), name="upload"),
    path("<str:file_name>/", FileDetailView.as_view(), name="detail"),
    path("latest-file", latest_file_view, name="latest-file"),
    path("file-converting", file_converting_view, name="file-converting"),
]

unite_compress/files/forms.py
from dal import autocomplete

from unite_compress.files.models import File
from unite_compress.files.widgets import DragAndDropFileInput


class FileForm(autocomplete.FutureModelForm):
    class Meta:
        model = File
        fields = ["file", "course"]
        widgets = {
            "file": DragAndDropFileInput(),
            "course": autocomplete.ModelSelect2(
                url="courses:autocomplete", attrs={"data-minimum-input-length": 0}
            ),
        }

unite_compress/files/api/views.py
from os import path

from django.conf import settings
from django.shortcuts import get_object_or_404
from rest_framework import mixins, serializers, status, viewsets
from rest_framework.decorators import action
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response
from rest_framework.views import APIView

from unite_compress.courses.models import Course
from unite_compress.files.api.serializers import AsyncResultSerializer, FileSerializer
from unite_compress.files.client import s3_generate_presigned_get
from unite_compress.files.mixins import ApiAuthMixin
from unite_compress.files.models import File
from unite_compress.files.services import (
    FileDirectUploadService,
    FileStandardUploadService,
)
from unite_compress.files.tasks import convert_file
from unite_compress.files.utils import Converter, convert_path


class FileViewSet(
    mixins.ListModelMixin,
    mixins.RetrieveModelMixin,
    mixins.DestroyModelMixin,
    viewsets.GenericViewSet,
):
    permission_classes = (IsAuthenticated,)
    queryset = File.objects.all()
    serializer_class = FileSerializer

    def get_queryset(self):
        return self.queryset.filter(uploaded_by=self.request.user)

    @action(
        detail=True,
        methods=["GET"],
    )
    def generate_url(self, request, pk):
        file = self.queryset.get(pk=pk)
        # TODO Fix: Hardecoded media
        if "S3" in settings.DEFAULT_FILE_STORAGE:
            file_path = convert_path("media/" + file.file.name)
            url = s3_generate_presigned_get(file_path=file_path)
        else:
            url = file.url

        response = Response(
            {"url": url},
            status=status.HTTP_200_OK,
            content_type="application/x-download",
        )
        dst_ext = path.splitext(file.converted_path)[1]
        dst_file_name = (
            f"{path.splitext(file.original_file_name)[0]}_compressed.{dst_ext}"
        )
        response["Content-Disposition"] = f'attachement; filename="{dst_file_name}"'

        return response

    def perform_destroy(self, instance):
        if instance.is_local:
            orig_file_path = instance.file.path
        else:
            orig_file_path = instance.file.name
        instance.file.storage.delete(orig_file_path)
        if instance.convert_status == "converted":
            conv_file_path = convert_path(orig_file_path)
            instance.file.storage.delete(conv_file_path)

        instance.delete()

    @action(detail=True, methods=["GET"])
    def tasks(self, request, pk):
        # Check if there are any existing tasks for the new model instance
        existing_tasks = convert_file.AsyncResult(str(pk))
        serializer = AsyncResultSerializer(existing_tasks)
        return Response(serializer.data, status=status.HTTP_200_OK)

    @action(detail=True, methods=["POST"])
    def convert(self, request, pk):
        file = self.queryset.get(pk=pk)
        # Check if there are any existing tasks for the new model instance
        if file.convert_status == "pending":
            # If no task exists, create a new task and return it
            compression_rate = request.query_params.get("compression_rate")
            try:
                command_id = Converter.choose_convert_command(file, compression_rate).id
            except AttributeError:
                message = "cannot convert: file type not supported"
                _status = status.HTTP_400_BAD_REQUEST
            else:
                task = convert_file.delay(command_id, pk)
                serializer = AsyncResultSerializer(task)
                return Response(
                    {"task": serializer.data, "message": "Task created"},
                    status=status.HTTP_201_CREATED,
                )
        else:
            if file.convert_status == "started":
                # Task exists, return message and status
                message = "File conversion in progress"
                _status = status.HTTP_204_NO_CONTENT
            elif file.convert_status == "converted":
                # File has been converted, return message and status
                message = "File has been converted"
                _status = status.HTTP_204_NO_CONTENT
            else:
                message = "File conversion error"
                _status = status.HTTP_500_INTERNAL_SERVER_ERROR
        return Response(
            {"message": message},
            status=_status,
        )


class FileStandardUploadApi(ApiAuthMixin, APIView):
    def post(self, request):
        service = FileStandardUploadService(
            user=request.user, file_obj=request.FILES["file"]
        )
        file = service.create()

        return Response(data={"id": file.id}, status=status.HTTP_201_CREATED)


class FileDirectUploadStartApi(ApiAuthMixin, APIView):
    class InputSerializer(serializers.Serializer):
        class UserFilteredPrimaryKeyRelatedField(serializers.PrimaryKeyRelatedField):
            def get_queryset(self):
                user = self.context["request"].user
                queryset = super().get_queryset()
                return queryset.filter(created_by=user)

        file_name = serializers.CharField()
        file_type = serializers.CharField()
        course = UserFilteredPrimaryKeyRelatedField(
            queryset=Course.objects.all(), allow_null=True
        )
        # course = serializers.PrimaryKeyRelatedField(queryset=Course.objects.all())

    def post(self, request, *args, **kwargs):
        serializer = self.InputSerializer(
            data=request.data, context={"request": request}
        )
        serializer.is_valid(raise_exception=True)

        service = FileDirectUploadService(request.user)
        presigned_data = service.start(**serializer.validated_data)

        return Response(data=presigned_data)


class FileDirectUploadLocalApi(ApiAuthMixin, APIView):
    def post(self, request, file_id):
        file = get_object_or_404(File, id=file_id)
        file_obj = request.FILES["file"]

        service = FileDirectUploadService(request.user)
        file = service.upload_local(file=file, file_obj=file_obj)

        return Response({"id": file.id})


class FileDirectUploadFinishApi(ApiAuthMixin, APIView):
    class InputSerializer(serializers.Serializer):
        file_id = serializers.CharField()

    def post(self, request):
        serializer = self.InputSerializer(data=request.data)
        serializer.is_valid(raise_exception=True)

        file_id = serializer.validated_data["file_id"]

        file = get_object_or_404(File, id=file_id)

        service = FileDirectUploadService(request.user)
        service.finish(file=file)

        return Response({"id": file.id})

unite_compress/files/views.py
from django.contrib import messages
from django.shortcuts import redirect, render
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView, FormView, ListView

from unite_compress.courses.models import Course
from unite_compress.files.forms import FileForm
from unite_compress.files.models import File


class FileListView(ListView):
    model = File
    template_name = "files/file_list.html"
    context_object_name = "files"

    def get_queryset(self):
        return File.objects.filter(uploaded_by=self.request.user)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["courses"] = Course.objects.filter(created_by=self.request.user)
        return context


class FileDetailView(DetailView):
    model = File
    template_name = "files/file_detail.html"
    context_object_name = "file"
    slug_url_kwarg = "file_name"
    slug_field = "file_name"


def latest_file_view(request):
    latest_file = File.objects.filter(uploaded_by=request.user).last()
    messages.success(request, _("Your file has been uploaded successfully."))
    return render(request, "files/file_detail.html", {"file": latest_file})


def file_converting_view(request):
    messages.success(request, _("Your file is being converted."))
    return redirect("files:list")


class FileUploadView(FormView):
    template_name = "files/file_upload.html"
    form_class = FileForm
    success_url = "files:list"

unite_compress/files/templates/files/file_detail.html
{% extends 'base.html' %}
{% load files_tags %}
{% load i18n %}
{% block title %} {% translate "File Detail" %} {% endblock %}

{% block javascript %}
    {{ block.super }}
    <script src="https://code.jquery.com/jquery-3.6.3.min.js" integrity="sha256-pvPw+upLPUjgMXY0G+8O0xUf+/Im1MZjXxxgOcBQBXU=" crossorigin="anonymous"></script>
{% endblock %}

{% block content %}
<div class="container tuto-box">
    <h1>{{ file.original_file_name }}</h1>
    <div class="table-responsive">
      <table class="table">
        <tbody>
          <tr>
            <td>
              <strong>{% translate "File Type:" %}</strong> {{ file.file_type }}
            </td>
          </tr>
          <tr>
            <td>
              <strong>{% translate "Created At:" %}</strong> {{ file.created_at | date:"d/m/Y G:i" }}
            </td>
          </tr>
          {% if file.original_file_size > 0 %}
          <tr>
            <td>
              <strong>{% translate "Original Size:" %}</strong> {{ file.original_file_size | filesizeformat }}
            </td>
          </tr>
          {% else %}
          <tr>
            <td>{% translate "File still uploading..." %}</td>
          </tr>
          {% endif %}
          {% if file.convert_status == "converted" and file.converted_file_size >= 1 %}
          <tr>
            <td>
              <strong>{% translate "Size after compression:" %}</strong> {{ file.converted_file_size | filesizeformat }} ({% percent_reduction file.file.size file.converted_file_size %}% reduction)
            </td>
          </tr>
          <tr>
            <td>
              <strong>{% translate "Converted At:" %}</strong> {{ file.converted_at }}
            </td>
          </tr>
          {% else %}
          <tr>
            <td>
              <strong>{% translate "Convert Status:" %}</strong> {{ file.convert_status }}
            </td>
          </tr>
          {% endif %}
        </tbody>
      </table>
    </div>
    {% if file.convert_status == "converted" %}
    <div class="btn-group" role="group">
      <button id="download-button" class="btn btn-primary" type="button">{% translate "Download" %}</button>
      <button id="delete-button" class="btn btn-danger" type="submit">{% translate "Delete" %}</button>
    </div>
    {% else %}
    <form>
        <div class="form-check">
            <label class="form-check-label">
              {% translate "Compression rate:" %}
            </label>
            <div class="d-flex flex-column">
              <div class="form-check">
                <input class="form-check-input" type="radio" name="conversion-rate" id="medium-rate" value="medium" checked>
                <label class="form-check-label" for="medium-rate">{% translate "Medium" %}</label>
              </div>
              <div class="form-check">
                <input class="form-check-input" type="radio" name="conversion-rate" id="high-rate" value="high">
                <label class="form-check-label" for="high-rate">{% translate "High" %}</label>
              </div>
            </div>
          </div>
      <div class="btn-group" role="group">
        <button id="convert-button" class="btn btn-primary" type="button">{% translate "Convert" %}</button>
        <button id="delete-button" class="btn btn-danger" type="submit">{% translate "Delete" %}</button>
      </div>

    </form>
    {% endif %}
    <div id="message"></div>
  </div>

{% endblock %}

{% block inline_javascript %}
<script>
    var message = $('#message');
    {% if file.convert_status == "converted" %}
        var downloadButton = $('#download-button');
        downloadButton.on('click', function() {
            $.getJSON("{% url 'api:file-generate-url' pk=file.id %}", function(data){
                var win = window.open(data.url, "_blank");
                win.focus();
            });
        });
    {% else %}
        var convertButton = $('#convert-button');
        convertButton.on('click', function() {
            var compressionRate = $("input[name=conversion-rate]:checked").val();
            message.html( 'Your file is converting.', compressionRate);
            $.ajax({
				url: "{% url 'api:file-convert' pk=file.id %}?compression_rate="+compressionRate,
				method: "POST",
                data: {},
                headers: {"X-CSRFToken": "{{ csrf_token }}"},
                success: function() {
					message.html('File conversion completed!');
                    window.location.replace("{% url 'files:file-converting' %}");
				},
                error: function(data) {
                    console.log(CSSStyleDeclaration)
					message.html(data.responseJSON.message);
				},
            });
        });
    {% endif %}
    var deleteButton = $('#delete-button');
        deleteButton.on('click', function() {
            $.ajax({
               url: "{% url 'api:file-detail' pk=file.id %}",
               type: "DELETE",
               headers: {"X-CSRFToken": "{{ csrf_token }}"},
               success: function(data){
                message.html('Successfully deleted');
                window.location.replace("{% url 'files:list' %}");
            }});
        });
</script>
{% endblock %}

unite_compress/files/templates/files/file_list.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}
{% block title %}File List{% endblock %}

{% block css %}
    {{ block.super }}
    <link href="{% static 'css/tables.css' %}" rel="stylesheet">
{% endblock css %}

{% block javascript %}
    {{ block.super }}
    <script src="https://code.jquery.com/jquery-3.6.3.min.js" integrity="sha256-pvPw+upLPUjgMXY0G+8O0xUf+/Im1MZjXxxgOcBQBXU=" crossorigin="anonymous"></script>
{% endblock %}

{% block content %}


<div class="container tuto-box">
    <h1> {% translate "File List" %} </h1>
    <p><a href="{% url 'files:upload' %}" class="btn btn-primary" role="button">{% translate "Upload new file" %}</a></p>

    <table class="table">
        <thead>
            <tr>
                <th><a href="#" data-sortby="name"> {% translate "File Name" %}</a></th>
                <th><a href="#" data-sortby="type">{% translate "File Type" %}</a></th>
                <th><a href="#" data-sortby="course">{% translate "Folder" %}</a></th>
                <th><a href="#" data-sortby="created">{% translate "Created At" %}</a></th>
                <th><a href="#" data-sortby="status">{% translate "Convert Status" %}</a></th>
				<th><a href="#" data-sortby="size">{% translate "Original Size" %}</a></th>
				<th><a href="#" data-sortby="size">{% translate "Size after compression" %}</a></th>
            </tr>
        </thead>
        <tbody id="fileTable">
            {% for file in files %}
                <tr class="file-row" data-course="{{ file.course.id }}">
                    <td><a href="{% url 'files:detail' file_name=file.file_name %}">{{ file.original_file_name }}</a></td>
                    <td>{{ file.file_type }}</td>
                    <td>
			{% if file.course %}
			    <a href="{% url 'courses:detail' course_slug=file.course.slug %}">{{ file.course }}</a>
			{% else %}
			       -
			{% endif %}
		    </td>
		    <td>{{ file.created_at  | date:"d/m/Y G:i"  }}</td>
			{% if file.convert_status == "started" %}
            	<td>{{ file.convert_status }} : {% translate "Refresh the page" %}</td>
			{% else %}
				<td>{{ file.convert_status }} </td>
			{% endif %}
			<td> {{ file.original_file_size | filesizeformat }} </td>
			<td> {{ file.converted_file_size | filesizeformat  }} </td>
		</tr>
            {% endfor %}
        </tbody>
    </table>
</div>

{% endblock %}
{% block inline_javascript %}
    <script>
	 $(document).ready(function() {
             $('th a').click(function(e) {
		 e.preventDefault();
		 var column = $(this).data('sortby');
		 var order = $(this).hasClass('asc') ? 'desc' : 'asc';
		 $('th a').removeClass('asc desc');
		 $(this).addClass(order);
		 $('th').removeClass('active-filter');
		 $(this).parent().addClass('active-filter');
		 sortTable(column, order);
             });
	 });


	     $('#courseSelect').on('change', function() {
		 var courseId = $(this).val();
		 if (courseId === 'all') {
		     $('#fileTable tr').show();
		 } else {
		     $('#fileTable tr').hide();
		     $('#fileTable tr[data-course="' + courseId + '"]').show();
		 }
	     });


	     function sortTable(column, order) {
		 var table = $('#fileTable');
		 var rows = table.find('tr').toArray();
		 rows.sort(function(a, b) {
		     var x = $(a).find('td:eq(' + getColumnIndex(column) + ')').text().toLowerCase();
		     var y = $(b).find('td:eq(' + getColumnIndex(column) + ')').text().toLowerCase();
		     if (x < y) { return order == 'asc' ? -1 : 1; }
		     if (x > y) { return order == 'asc' ? 1 : -1; }
		     return 0;
		 });
		 $.each(rows, function(index, row) {
		     table.append(row);
		 });
	     }


	     function getColumnIndex(column) {
		 switch (column) {
		     case 'name': return 0;
		     case 'type': return 1;
		     case 'course': return 2;
		     case 'created': return 3;
		     case 'status': return 4;
			 case 'size': return 4;
		 }
	     }

    </script>
{% endblock %}

unite_compress/files/templates/files/file_upload.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}
{% block title %} {% translate "File Upload" %} {% endblock %}

{% block css %}
    {{ block.super }}
    <link href="{% static 'css/spinner.css' %}" rel="stylesheet">
{% endblock css %}

{% block content %}
<div class="tuto-box tuto-box">

    <form id="file-upload-form" method="post" enctype="multipart/form-data">
	{% csrf_token %}
	{{ form.as_p }}
	<input class="btn btn-primary" type="submit" value='{% translate "Save" %}' /> </form>
    </form>
    <div id="messages"></div>
    <div id="uploading-spinner" class="uploading-spinner hidden">
	<img src="{% static 'images/spinner.gif' %}" alt="Uploading...">
	<span>  "Uploading..." </span>
    </div>

	<br>
	<ul>
		<p> {% translate "The platform supports the following mime types :" %}  </p>
		<li>{% translate "application / pdf" %}   </li>
		<li> {% translate "image" %} /* </li>
		<li> {% translate "video" %} /* </li>
	</ul>
	</div>
{% endblock content %}

{% block inline_javascript %}
    <script src="https://code.jquery.com/jquery-3.6.3.min.js" integrity="sha256-pvPw+upLPUjgMXY0G+8O0xUf+/Im1MZjXxxgOcBQBXU=" crossorigin="anonymous"></script>
    {{ form.media }}
    <script>
     $(document).ready(function() {
	 var form = $('#file-upload-form');
	 var messages = $('#messages');
	 var spinner = $('#uploading-spinner');
	 $(form).on("submit", function(event) {
	     event.preventDefault();
	     var file = form.find("input[type=file]").get(0).files[0];

             if (file) {
		 spinner.removeClass('hidden'); // display the spinner
		 var fileName = file.name;
		 var fileType = file.type;
		 var courseId = form.find("select[name=course]").find(":selected").val();

		 $.ajax({
		     url: "{% url 'api:file-upload:upload:direct:start' %}",
		     method: "POST",
		     data: { file_name: fileName, file_type: fileType, course: courseId },
		     success: function(response) {
			 //var data = response.data;
			 var postData = new FormData();
			 var fields = response.fields;
			 for (var key in fields){
			     postData.append(key, fields[key]);
			 }
			 postData.append('file', file);
			 messages.html('File is uploading');
			 $.ajax({
			     url: response.url,
			     method: 'POST',
			     data: postData,
			     processData: false,
			     contentType: false,
			     success: function() {
				 $.ajax({
				     url: "{% url 'api:file-upload:upload:direct:finish' %}",
				     method: 'POST',
				     data: { file_id: response.id },
				     success: function() {
					 messages.html('File upload completed!');
					 window.location.href="{% url 'files:latest-file' %}";
					 spinner.addClass('hidden'); // hide the spinner
				     },
				     error: function() {
					 messages.html('1File upload failed!');
					 spinner.addClass('hidden');
				     }
				 });
			     },
			     error: function() {
				 messages.html('2File upload failed!');
				 spinner.addClass('hidden');
			     }
			 });
		     },
		     error: function() {
			 messages.html('3File upload failed!');
			 spinner.addClass('hidden');
		     }
		 });
	     }
	 });
     });
    </script>
{% endblock inline_javascript %}