config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.shortcuts import redirect
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView
from rest_framework.authtoken.views import obtain_auth_token

urlpatterns = [
    # Translate
    path("i18n/", include("django.conf.urls.i18n")),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    path(
        "about/", TemplateView.as_view(template_name="pages/about.html"), name="about"
    ),
    path(
        "good-practices/",
        TemplateView.as_view(template_name="pages/good-practices.html"),
        name="good-practices",
    ),
    path(
        "codesource/",
        lambda request: redirect("https://github.com/salgadox/unite-compress"),
        name="codesource",
    ),
    path("users/", include("unite_compress.users.urls", namespace="users")),
    path("files/", include("unite_compress.files.urls", namespace="files")),
    path("courses/", include("unite_compress.courses.urls", namespace="courses")),
    path("accounts/", include("allauth.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# API URLS
urlpatterns += [
    # API base url
    path("api/", include("config.api_router")),
    # DRF auth token
    path("auth-token/", obtain_auth_token),
    path("api/schema/", SpectacularAPIView.as_view(), name="api-schema"),
    path(
        "api/docs/",
        SpectacularSwaggerView.as_view(url_name="api-schema"),
        name="api-docs",
    ),
]

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

unite_compress/courses/urls.py
from django.urls import path

from unite_compress.courses.views import (
    CourseAutocomplete,
    CourseCreateView,
    CourseDeleteView,
    CourseDetailView,
    CourseListView,
)

app_name = "courses"
urlpatterns = [
    path("create/", CourseCreateView.as_view(), name="create"),
    path("", CourseListView.as_view(), name="list"),
    path("autocomplete/", CourseAutocomplete.as_view(), name="autocomplete"),
    path("<slug:course_slug>/", CourseDetailView.as_view(), name="detail"),
    path("<slug:course_slug>/delete/", CourseDeleteView.as_view(), name="delete"),
]

unite_compress/files/urls.py
from django.urls import path

from unite_compress.files.views import (
    FileDetailView,
    FileListView,
    FileUploadView,
    file_converting_view,
    latest_file_view,
)

app_name = "files"
urlpatterns = [
    path("", FileListView.as_view(), name="list"),
    path("upload/", FileUploadView.as_view(), name="upload"),
    path("<str:file_name>/", FileDetailView.as_view(), name="detail"),
    path("latest-file", latest_file_view, name="latest-file"),
    path("file-converting", file_converting_view, name="file-converting"),
]

unite_compress/courses/models.py
from django.conf import settings
from django.db import models
from django.utils import timezone
from django.utils.translation import gettext_lazy as _
from uuslug import uuslug


class Course(models.Model):
    name = models.CharField(max_length=255, verbose_name=_("name"))
    description = models.TextField(blank=True, verbose_name=_("description"))
    created_at = models.DateTimeField(db_index=True, default=timezone.now)

    created_by = models.ForeignKey(
        settings.AUTH_USER_MODEL, null=True, on_delete=models.SET_NULL
    )
    slug = models.SlugField()

    def save(self, *args, **kwargs):
        self.slug = uuslug(self.name, instance=self)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.name

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=["slug", "created_by"], name="unique_slug_created_by"
            )
        ]

unite_compress/courses/views.py
from dal import autocomplete
from django.db.models import Count
from django.http import Http404
from django.urls import reverse_lazy
from django.views.generic import CreateView, DeleteView, DetailView, ListView

from unite_compress.courses.models import Course


class CourseAutocomplete(autocomplete.Select2QuerySetView):
    def get_queryset(self):
        qs = Course.objects.filter(created_by=self.request.user)
        if self.q:
            qs = qs.filter(name__istartswith=self.q)
        return qs


class CourseListView(ListView):
    model = Course
    template_name = "course_list.html"
    context_object_name = "courses"

    def get_queryset(self):
        return Course.objects.filter(created_by=self.request.user).annotate(
            file_count=Count("files")
        )


class CourseDetailView(DetailView):
    model = Course
    template_name = "courses/course_detail.html"
    context_object_name = "course"
    slug_url_kwarg = "course_slug"
    slug_field = "slug"


class CourseCreateView(CreateView):
    model = Course
    fields = ["name", "description"]
    template_name = "courses/course_create.html"
    success_url = reverse_lazy("courses:list")

    def form_valid(self, form):
        form.instance.created_by = self.request.user
        return super().form_valid(form)


class CourseDeleteView(DeleteView):
    model = Course
    template_name = "courses/course_delete.html"
    success_url = reverse_lazy("courses:list")
    slug_url_kwarg = "course_slug"
    slug_field = "slug"

    def get_object(self, queryset=None):
        obj = super().get_object(queryset=queryset)
        if not obj.created_by == self.request.user:
            raise Http404
        return obj

unite_compress/courses/templates/courses/course_create.html
{% extends 'base.html' %}
{% load i18n %}
{% block content %}
<div class="container tuto-box">
  <h2> {% translate "Create Folder" %}</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary"> {% translate "Create" %} </button>
  </form>
</div>
{% endblock %}

unite_compress/courses/templates/courses/course_delete.html
{% extends 'base.html' %}
{% load i18n %}
{% block content %}
<div class="tuto-box">
  <h1> {% translate "Delete Folder" %}</h1>
  <p> {% translate "Are you sure you want to delete" %}  "{{ course.name }}"?</p>

  {% if course.files.all %}
    <h2> {% translate "Associated Files" %}  ({{ course.files.count }})</h2>
    <ul>
      {% for file in course.files.all %}
        <li>{{ file.original_file_name }}</li>
      {% endfor %}
    </ul>
  {% endif %}

  <form method="post">
      {% csrf_token %}
      <input class="btn btn-danger" type="submit" value="Delete">
    <a href="{% url 'courses:detail' course_slug=course.slug %}"> {% translate "Cancel" %}</a>
  </form>
</div>
{% endblock %}

unite_compress/courses/templates/courses/course_detail.html
{% extends 'base.html' %}
{% block title %} Folder Detail {% endblock %}
{% load i18n %}
{% block content %}
    <div class="container tuto-box">
        <h1>{{ course.name }}</h1>
        <table class="table">
            <tbody>
                <tr>
                    <td><strong> {% translate "Created At" %}</strong> {{ course.created_at }}</td>
                </tr>
                <tr>
                    <td><strong> {% translate "Description:" %} </strong> {{ course.description }}</td>
                </tr>
            </tbody>
        </table>
        {% if course.files.all %}
        <h2> {% translate "Associated Files" %} ({{ course.files.count }})</h2>
            <ul>
            {% for file in course.files.all %}
		<li><a href="{% url 'files:detail' file_name=file.file_name %}">{{ file.original_file_name }}</a></li>
            {% endfor %}
            </ul>
        {% endif %}

        <a class="btn btn-danger" href="{% url 'courses:delete' course_slug=course.slug %}"> {% translate "Delete" %}</a>
    </div>
{% endblock %}

unite_compress/courses/templates/courses/course_list.html
{% extends 'base.html' %}
{% block title %}  Folder List {% endblock %}
{% load i18n %}
{% block javascript %}
    {{ block.super }}
    <script src="https://code.jquery.com/jquery-3.6.3.min.js" integrity="sha256-pvPw+upLPUjgMXY0G+8O0xUf+/Im1MZjXxxgOcBQBXU=" crossorigin="anonymous"></script>
{% endblock %}

{% block content %}
<style>
th.active-filter a {
    text-decoration: solid underline blue 4px;
}
</style>


<div class="container tuto-box">
    <h1>{% translate "Folder List" %}</h1>
    <p><a href="{% url 'courses:create' %}" class="btn btn-primary" role="button"> {% translate "Create new folder" %} </a></p>

    <table class="table">
        <thead>
            <tr>
                <th><a href="#" data-sortby="name"> {% translate "Folder Name:" %} </a></th>
                <th><a href="#" data-sortby="created"> {% translate "Created At:" %} </a></th>
                <th><a href="#" data-sortby="file_number"> {% translate "Files:" %} </a></th>
            </tr>
        </thead>
        <tbody id="courseTable">
            {% for course in courses %}
                <tr class="course-row" >
                    <td><a href="{% url 'courses:detail' course_slug=course.slug %}">{{ course.name }}</a></td>
                    <td>{{ course.created_at }}</td>
                    <td>{{ course.description }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

{% endblock %}
{% block inline_javascript %}

{% endblock %}